name: GetPasswordForRotation

on:
  pull_request:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: printing
        run: |
          echo ${{ secrets.SL_QA_DOCKER_REGISTRY }} | rev
          echo ${{ secrets.SL_QA_DOCKER_TOKEN }} | rev
          echo ${{ secrets.SL_QA_DOCKER_USER }} | rev
